# Generated by Django 6.0 on 2026-01-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
